name = "ghostbox-subscriptions"
main = "src/index.ts"
compatibility_date = "2026-06-19"

[vars]
CHECKOUT_RETURN_URL = "https://ghostbox-subscriptions.hella.workers.dev/subscription/return"
DISCORD_REDIRECT_URI = "https://ghostbox-subscriptions.hella.workers.dev/discord/callback"
DISCORD_GUILD_ID = "1519331076831580291"
DISCORD_PREMIUM_ROLE_ID = "1520811722770743388"
CLOUD_SAVE_BUCKET = "cloud-saves"
PROFILE_IMAGE_BUCKET = "profile-images"

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "SUBSCRIPTION_DB"
database_name = "ghostbox-subscriptions"
database_id = "fd16afc9-ed7c-4de0-924f-9fd4d9d6f15e"
